version: "3.9"
services:
  db:
    image: postgres:13.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U udv_test"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=udv_test
      - POSTGRES_USER=udv_test
      - POSTGRES_PASSWORD=password

  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=udv_test
      - PORT=:8000
      - DATABASE_PASSWORD=password
      - DATABASE_USER=udv_test
    links:
      - db